version: "3"

services:
  api:
    build: ./
    command: "npx nest start --watch --debug=0.0.0.0:9229"
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
