version: "3"

services:
  api:
    build:
      context: ./
      target: development
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app:ro
      - /usr/src/app/node_modules
      - /usr/src/app/dist
