services:
  api:
    build:
      context: ./
      target: development
    command: ["npx", "nest", "start", "--watch", "--debug", "0.0.0.0:9229"]
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "9229:9229"
    user: node
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
